on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
  
name: Build and test

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build and test
      run: |
        cargo build --release
        cargo test
      